import type { Theme } from '@/types/colors';

export const CURATED_THEMES: Theme[] = [
  {
    id: 'green-meadow',
    name: 'Green Meadow',
    hebrewName: 'שדה ירוק',
    tier: 'free',
    colors: {
      primaryText: '#333333',
      secondaryText: '#666666',
      link: '#10B981',
      code: '#064E3B',
      h1: '#064E3B',
      h1Border: '#10B981',
      h2: '#064E3B',
      h2Border: '#10B981',
      h3: '#0D9668',
      previewBg: '#FAFAF5',
      codeBg: '#0A2E1F',
      blockquoteBg: '#F2F8F3',
      tableHeader: '#E8F5EE',
      tableAlt: '#F3F3EE',
      blockquoteBorder: '#10B981',
      hr: '#C8CCC5',
      tableBorder: '#C8CCC5',
    },
  },
  {
    id: 'sea-of-galilee',
    name: 'Sea of Galilee',
    hebrewName: 'ים כנרת',
    tier: 'free',
    colors: {
      primaryText: '#1A3A3F',
      secondaryText: '#4A6A70',
      link: '#14B8A6',
      code: '#0D4F5A',
      h1: '#0D4F5A',
      h1Border: '#14B8A6',
      h2: '#0D4F5A',
      h2Border: '#14B8A6',
      h3: '#1A7A7A',
      previewBg: '#F2F8F7',
      codeBg: '#0A2A2E',
      blockquoteBg: '#E8F5F3',
      tableHeader: '#DCF0EC',
      tableAlt: '#EBF2F1',
      blockquoteBorder: '#14B8A6',
      hr: '#B8C8C5',
      tableBorder: '#B8C8C5',
    },
  },
  {
    id: 'minimal-gray',
    name: 'Minimal Gray',
    hebrewName: 'אפור מינימלי',
    tier: 'free',
    colors: {
      primaryText: '#1F2937',
      secondaryText: '#4B5563',
      link: '#6B7280',
      code: '#374151',
      h1: '#1F2937',
      h1Border: '#6B7280',
      h2: '#1F2937',
      h2Border: '#6B7280',
      h3: '#374151',
      previewBg: '#FAFAFA',
      codeBg: '#111827',
      blockquoteBg: '#F3F4F6',
      tableHeader: '#E5E7EB',
      tableAlt: '#F3F4F6',
      blockquoteBorder: '#6B7280',
      hr: '#D1D5DB',
      tableBorder: '#D1D5DB',
    },
  },
  {
    id: 'old-parchment',
    name: 'Old Parchment',
    hebrewName: 'קלף ישן',
    tier: 'premium',
    colors: {
      primaryText: '#4A3520',
      secondaryText: '#7A6550',
      link: '#D97706',
      code: '#78350F',
      h1: '#78350F',
      h1Border: '#D97706',
      h2: '#78350F',
      h2Border: '#D97706',
      h3: '#92400E',
      previewBg: '#F5ECD7',
      codeBg: '#2C1A08',
      blockquoteBg: '#EFE4CC',
      tableHeader: '#E8D9BA',
      tableAlt: '#EEE5D0',
      blockquoteBorder: '#D97706',
      hr: '#C8B896',
      tableBorder: '#C8B896',
    },
  },
  {
    id: 'negev-night',
    name: 'Negev Night',
    hebrewName: 'לילה בנגב',
    tier: 'premium',
    colors: {
      primaryText: '#E2E0F0',
      secondaryText: '#9896B0',
      link: '#F59E0B',
      code: '#FCD34D',
      h1: '#FCD34D',
      h1Border: '#F59E0B',
      h2: '#FCD34D',
      h2Border: '#F59E0B',
      h3: '#E8C547',
      previewBg: '#1A1B2E',
      codeBg: '#0E0F1E',
      blockquoteBg: '#242538',
      tableHeader: '#2E2F44',
      tableAlt: '#212234',
      blockquoteBorder: '#F59E0B',
      hr: '#3A3B52',
      tableBorder: '#3A3B52',
    },
  },
  {
    id: 'soft-rose',
    name: 'Soft Rose',
    hebrewName: 'ורד רך',
    tier: 'premium',
    colors: {
      primaryText: '#4A2030',
      secondaryText: '#7A5060',
      link: '#F43F5E',
      code: '#9F1239',
      h1: '#9F1239',
      h1Border: '#F43F5E',
      h2: '#9F1239',
      h2Border: '#F43F5E',
      h3: '#BE185D',
      previewBg: '#FFF5F0',
      codeBg: '#2E0A18',
      blockquoteBg: '#FEEAE5',
      tableHeader: '#FDD8CF',
      tableAlt: '#FEEEE9',
      blockquoteBorder: '#F43F5E',
      hr: '#D4B8B0',
      tableBorder: '#D4B8B0',
    },
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    hebrewName: 'חלום לבנדר',
    tier: 'premium',
    colors: {
      primaryText: '#3B1A6E',
      secondaryText: '#6B4A9E',
      link: '#8B5CF6',
      code: '#5B21B6',
      h1: '#5B21B6',
      h1Border: '#8B5CF6',
      h2: '#5B21B6',
      h2Border: '#8B5CF6',
      h3: '#7C3AED',
      previewBg: '#F5F3FF',
      codeBg: '#1E0E3E',
      blockquoteBg: '#EDE9FE',
      tableHeader: '#DDD6FE',
      tableAlt: '#EDE9FE',
      blockquoteBorder: '#8B5CF6',
      hr: '#C4B5E0',
      tableBorder: '#C4B5E0',
    },
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    hebrewName: 'עומק האוקיינוס',
    tier: 'premium',
    colors: {
      primaryText: '#1A2E4A',
      secondaryText: '#4A6A8A',
      link: '#3B82F6',
      code: '#1E3A5F',
      h1: '#1E3A5F',
      h1Border: '#3B82F6',
      h2: '#1E3A5F',
      h2Border: '#3B82F6',
      h3: '#2D5A8F',
      previewBg: '#EFF6FF',
      codeBg: '#0E1E30',
      blockquoteBg: '#DBEAFE',
      tableHeader: '#BFDBFE',
      tableAlt: '#E5EEFF',
      blockquoteBorder: '#3B82F6',
      hr: '#A8BDD0',
      tableBorder: '#A8BDD0',
    },
  },
];

export const CURATED_THEME_MAP: Record<string, Theme> = Object.fromEntries(
  CURATED_THEMES.map((t) => [t.id, t])
);

export const DEFAULT_THEME_ID = 'green-meadow';

export function canApplyTheme(theme: Theme, userTier: 'free' | 'paid' | 'anonymous' | 'loading'): boolean {
  if (theme.tier === 'free') return true;
  if (userTier === 'loading') return true; // permissive during auth loading
  return userTier === 'paid';
}
